### ISSUE TITLE
can you make a first 1.0.0 version

### ISSUE THREAD

**Issue by timmit-nl** [Martijnc/php-csp#1]
Hi Martijn,

I am using your CSP class and it works great. But can you make a first 1.0.0 version of this one? Now I can't include it as an requirement in my applications.

Thanks,

Tim

**Comment by timmit-nl** [comment]
Sorry I was not clear. You also need to make a release in github. You can do that with making a tag v1.0.0 with the current master as source. Then will the packagist pick it up. But thanks for the quick response!

**Comment by Martijnc** [comment]
Like this: https://github.com/Martijnc/php-csp/releases?

**Comment by timmit-nl** [comment]
Yes thats it!
(en aangezien je Vlaams bent: heel erg bedankt!)
