### ISSUE TITLE
worker-src missing

### ISSUE THREAD

**Issue by pkollitsch** [martijnc/php-csp#4]
There is a CSP for worker-src that seems to be missing from ContentSecurityPolicyHeaderBuilder.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src

Is it omitted by design or a newer feature than the class?

**Comment by martijnc** [comment]
worker-src was added to CSP after this library was written and as it isn't maintained anymore it was never added.

If you are looking for a PHP library to create CSP headers you might want to take a look at https://github.com/paragonie/csp-builder.
